In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [4]:
#2. Print the NUMPY version and the configuration.
print (np.__version__)
print (np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/davidusuariocasa/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/davidusuariocasa/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/davidusuariocasa/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/davidusuariocasa/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/davidusuariocasa/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/davidusuariocasa/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/davidusuariocasa/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/davidusuariocasa/o

In [15]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
dimensiones = (2, 3, 5)

a = np.random.random_sample(dimensiones)

primera = np.random.rand(2, 3, 5)



array([[[0.61104811, 0.94611983, 0.09895429, 0.41732617, 0.25090011],
        [0.21799631, 0.3948775 , 0.21984714, 0.77866128, 0.09557261],
        [0.67355459, 0.30871322, 0.68414027, 0.00257047, 0.67312623]],

       [[0.96451843, 0.01676667, 0.14933448, 0.52278576, 0.17551695],
        [0.7884808 , 0.22619775, 0.53808967, 0.85295868, 0.23967149],
        [0.26832925, 0.89045097, 0.13454317, 0.43737317, 0.07743772]]])

In [16]:
#4. Print a.
a

array([[[0.02115301, 0.95312592, 0.63008945, 0.74486801, 0.77615472],
        [0.38058165, 0.56675042, 0.94750926, 0.35018012, 0.96435806],
        [0.25182315, 0.70350433, 0.56992279, 0.84825986, 0.11148365]],

       [[0.91408877, 0.40172806, 0.65743537, 0.77644988, 0.43320633],
        [0.51531544, 0.27061746, 0.25794833, 0.81231893, 0.57038358],
        [0.90874863, 0.87166842, 0.19032651, 0.2919613 , 0.67815607]]])

In [19]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [23]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size == b.size


True

In [26]:
#8. Are you able to add a and b? Why or why not?

#no se puede porque tienen dimensiones diferentes

ValueError: operands could not be broadcast together with shapes (5,3,2) (5,2,3) 

In [33]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b, (1, 2, 0))

In [60]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c

# it works because their dimensions match

In [39]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)

print(d)

[[[0.02115301 0.95312592 0.63008945 0.74486801 0.77615472]
  [0.38058165 0.56675042 0.94750926 0.35018012 0.96435806]
  [0.25182315 0.70350433 0.56992279 0.84825986 0.11148365]]

 [[0.91408877 0.40172806 0.65743537 0.77644988 0.43320633]
  [0.51531544 0.27061746 0.25794833 0.81231893 0.57038358]
  [0.90874863 0.87166842 0.19032651 0.2919613  0.67815607]]]
[[[1.02115301 1.95312592 1.63008945 1.74486801 1.77615472]
  [1.38058165 1.56675042 1.94750926 1.35018012 1.96435806]
  [1.25182315 1.70350433 1.56992279 1.84825986 1.11148365]]

 [[1.91408877 1.40172806 1.65743537 1.77644988 1.43320633]
  [1.51531544 1.27061746 1.25794833 1.81231893 1.57038358]
  [1.90874863 1.87166842 1.19032651 1.2919613  1.67815607]]]


In [41]:
#12. Multiply a and c. Assign the result to e.

e = a * c


array([[[0.02115301, 0.95312592, 0.63008945, 0.74486801, 0.77615472],
        [0.38058165, 0.56675042, 0.94750926, 0.35018012, 0.96435806],
        [0.25182315, 0.70350433, 0.56992279, 0.84825986, 0.11148365]],

       [[0.91408877, 0.40172806, 0.65743537, 0.77644988, 0.43320633],
        [0.51531544, 0.27061746, 0.25794833, 0.81231893, 0.57038358],
        [0.90874863, 0.87166842, 0.19032651, 0.2919613 , 0.67815607]]])

In [42]:
#13. Does e equal to a? Why or why not?

#yes, they are equal, because you are multiplying a by 1

array([[[0.02115301, 0.95312592, 0.63008945, 0.74486801, 0.77615472],
        [0.38058165, 0.56675042, 0.94750926, 0.35018012, 0.96435806],
        [0.25182315, 0.70350433, 0.56992279, 0.84825986, 0.11148365]],

       [[0.91408877, 0.40172806, 0.65743537, 0.77644988, 0.43320633],
        [0.51531544, 0.27061746, 0.25794833, 0.81231893, 0.57038358],
        [0.90874863, 0.87166842, 0.19032651, 0.2919613 , 0.67815607]]])

In [44]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)



1.5790039166631222

In [67]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2, 3, 5), dtype = str)

f



array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [73]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
'''If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
'''

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value > d_min and value < d_mean:
                f[i, j, k] = 25
            elif value > d_mean and value < d_max:
                f[i, j, k] = 75
            elif value == d_mean:
                f[i, j, k] = 50
            elif value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
                
f



array([[['0', '7', '7', '7', '7'],
        ['2', '2', '7', '2', '1'],
        ['2', '7', '2', '7', '2']],

       [['7', '2', '7', '7', '2'],
        ['2', '2', '2', '7', '2'],
        ['7', '7', '2', '2', '7']]], dtype='<U1')