In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [4]:
#2. Print the NUMPY version and the configuration.

print('Numpy version', np.__version__)

print('Numpy configuration:')

print(np.show_config())

Numpy version 1.23.5
Numpy configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/veronicamoncada/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/veronicamoncada/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/veronicamoncada/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/veronicamoncada/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    foun

In [7]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.rand(2, 3, 5)

print (a)

[[[0.45903858 0.89148101 0.50294407 0.23100222 0.43033105]
  [0.14605464 0.65527292 0.80271409 0.41201287 0.01956378]
  [0.17405893 0.99604293 0.8578964  0.47486763 0.03349679]]

 [[0.97478823 0.14662356 0.00803548 0.58842188 0.71800807]
  [0.13022726 0.81008668 0.14865979 0.17513357 0.10110561]
  [0.36388669 0.73272404 0.1062318  0.76064662 0.60160712]]]


In [8]:
a = np.random.randn(2, 3, 5)

print (a)

[[[ 0.41880656 -0.48459219  0.41230678 -1.1424129  -0.27512112]
  [ 0.05755879 -0.85683102  0.47753933 -0.99844484 -0.86192886]
  [ 0.55525789 -1.32735031  0.82161229  0.9475071   0.53461324]]

 [[-0.54943021  0.55766461  1.25999663 -0.02428416 -0.27858845]
  [ 0.63447391 -0.95375749 -1.80899485 -0.38843784  1.01486476]
  [-0.68888694  0.56926575 -0.96781266  0.84097979 -0.18777473]]]


In [9]:
a = np.random.random_sample((2, 3, 5))

print(a)

[[[0.17515332 0.24326526 0.15694728 0.3094235  0.95641533]
  [0.457233   0.57004941 0.98974303 0.6911829  0.64650684]
  [0.38115842 0.34905633 0.99029817 0.48356186 0.59500361]]

 [[0.54069972 0.31951174 0.95932312 0.68955641 0.84479876]
  [0.31040161 0.30711163 0.68444956 0.00264807 0.36076726]
  [0.65050466 0.50631076 0.31134523 0.504406   0.34159404]]]


In [ ]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

