1. Import the NUMPY package under the name np.

In [3]:
import numpy as np

2. Print the NUMPY version and the configuration.

In [4]:
print(np.__version__)
print(np.show_config())

1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/STF/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/STF/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/STF/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/STF/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/STF/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/STF/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/STF/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/STF/anaconda3\\Library\\inc

3. Genera una matriz tridimensional 2x3x5 con valores aleatorios. Asigna el arreglo a la variable "a".

In [5]:
a = np.random.random((3,2,5))
a

array([[[0.00550821, 0.07417117, 0.83432173, 0.34577146, 0.05123209],
        [0.5039223 , 0.99534268, 0.1603097 , 0.09384193, 0.44810038]],

       [[0.62141364, 0.20106772, 0.68329497, 0.96875763, 0.56051962],
        [0.02776128, 0.35013522, 0.57976256, 0.2164994 , 0.56371725]],

       [[0.57863805, 0.25849108, 0.7694041 , 0.88466783, 0.74222569],
        [0.09044981, 0.60514093, 0.81166067, 0.15924428, 0.69933908]]])

In [6]:
# Desafío: hay al menos tres formas sencillas que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar?

matriz1 = np.random.rand(3,2,5)
matriz1

array([[[0.97373935, 0.9225673 , 0.7077919 , 0.4401987 , 0.03969072],
        [0.87223483, 0.97513117, 0.13749873, 0.56395817, 0.45106462]],

       [[0.34560978, 0.2905806 , 0.94552339, 0.64092406, 0.07637061],
        [0.19497117, 0.26977235, 0.06412665, 0.87271285, 0.28551236]],

       [[0.19525533, 0.40124041, 0.75598287, 0.61836247, 0.07617689],
        [0.48420333, 0.22216978, 0.69309213, 0.83666938, 0.21934449]]])

In [7]:
matriz2 = np.random.randn(3,2,5)
matriz2

array([[[ 0.1785001 ,  0.30032   ,  1.29450254,  0.61666064,
         -0.3948459 ],
        [ 0.04689614, -0.83131496,  1.62326398,  0.79086559,
         -0.18682263]],

       [[-0.32606039,  0.57506501, -0.1907122 , -0.35318374,
          0.79859289],
        [ 0.63347757,  0.29581041,  1.62513877,  0.77807615,
          1.29504719]],

       [[ 1.39020172, -0.66013321,  0.50456083,  1.05596473,
         -0.03177585],
        [-0.74745788,  0.9853273 , -0.05993342,  2.69707993,
          0.78307804]]])

In [8]:
matriz3 = np.random.randint(low=0, high=10, size=(3, 2, 5))
matriz3

array([[[5, 2, 6, 5, 9],
        [1, 8, 1, 3, 5]],

       [[1, 0, 3, 8, 8],
        [8, 5, 2, 4, 2]],

       [[2, 3, 7, 2, 9],
        [4, 4, 2, 4, 8]]])

4. Print a.

In [9]:
print(a)

[[[0.00550821 0.07417117 0.83432173 0.34577146 0.05123209]
  [0.5039223  0.99534268 0.1603097  0.09384193 0.44810038]]

 [[0.62141364 0.20106772 0.68329497 0.96875763 0.56051962]
  [0.02776128 0.35013522 0.57976256 0.2164994  0.56371725]]

 [[0.57863805 0.25849108 0.7694041  0.88466783 0.74222569]
  [0.09044981 0.60514093 0.81166067 0.15924428 0.69933908]]]


5. Crea una matriz tridimensional 5x2x3 con todos los valores iguales a 1.

In [10]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [19]:
#Assign the array to variable "b"

b = np.ones((5, 2, 3), int)

6. Print b.

In [12]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


7. ¿Tienen a y b el mismo tamaño? ¿Cómo demostrarlo en código Python?

In [13]:
a.shape == b.shape

False

8. ¿Eres capaz de sumar a y b? ¿Por qué sí o por qué no?

In [ ]:
# No, debido a que no tienen las mismas dimensiones.

9. Transpón b para que tenga la misma estructura que a (es decir, que se convierta en un array 2x3x5). Asigna el array transpuesto a la variable "c".

In [20]:
c = b.T
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". ¿Pero por qué funciona ahora?

In [22]:
d = np.add(a, c)

11. Imprime a y d. ¿Notas la diferencia y relación de las dos matrices en cuanto a los valores? Explícalo.

In [61]:
print(a)
print(d)

[[[0.00550821 0.07417117 0.83432173 0.34577146 0.05123209]
  [0.5039223  0.99534268 0.1603097  0.09384193 0.44810038]]

 [[0.62141364 0.20106772 0.68329497 0.96875763 0.56051962]
  [0.02776128 0.35013522 0.57976256 0.2164994  0.56371725]]

 [[0.57863805 0.25849108 0.7694041  0.88466783 0.74222569]
  [0.09044981 0.60514093 0.81166067 0.15924428 0.69933908]]]
[[[1.00550821 1.07417117 1.83432173 1.34577146 1.05123209]
  [1.5039223  1.99534268 1.1603097  1.09384193 1.44810038]]

 [[1.62141364 1.20106772 1.68329497 1.96875763 1.56051962]
  [1.02776128 1.35013522 1.57976256 1.2164994  1.56371725]]

 [[1.57863805 1.25849108 1.7694041  1.88466783 1.74222569]
  [1.09044981 1.60514093 1.81166067 1.15924428 1.69933908]]]


La diferencia entre las dos matrices en cuanto a valor es "1", ya que le hemos sumado 1 a cada valor de "a" a través de la matriz unitaria "c", siendo el resultado "d"

Las dimensiones son las mismas ya que la resultante de la suma de dos matrices, las cuales tienen que tener la misma dimensión, es una tercera matriz de igual dimensión.

12. Multiplica a y c. Asigna el resultado a e.

In [ ]:
e = np.multiply(a,c)
e

13. ¿Es e igual a a? ¿Por qué sí o por qué no?

In [ ]:
e == a 

Si, son iguales por que practicamente lo que hemos hecho es multiplicar a "a" por 1

14. Identifica los valores máximo, mínimo y media de d. Asigna esos valores a las variables "d_máx", "d_mín" y "d_media".

In [56]:
d_max = np.min(d)
d_min = np.max(d)
d_media = np.mean(d)
print(f'El máximo de d es: {d_max}')
print(f'El mínimo de d es: {d_min}')
print(f'La media de d es: {d_media}')

El máximo de d es: 1.0055082061937068
El mínimo de d es: 1.995342678545915
La media de d es: 1.4628237483101516


15. Ahora queremos etiquetar los valores de d. Primero crea una matriz vacía "f" con la misma forma (es decir, 2x3x5) que d utilizando `np.empty`.

In [28]:
f = np.empty((3,2,5), dtype = int)
f = []

In [55]:
f = np.zeros_like(d)
f.shape == d.shape

True

16. Rellena los valores en f. 

+ Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.

+ Si un valor en d es mayor que d_medio pero menor que d_máx, asigna 75 al valor correspondiente en f.

+ Si un valor es igual a d_medio, asigne 50 al valor correspondiente en f.

+ Asigne 0 al valor o valores correspondientes en f para d_min en d.

+ Asigne 100 al valor o valores correspondientes en f para d_max en d.

Al final, f debería tener sólo los siguientes valores: 0, 25, 50, 75 y 100.

Nota: no tienes que usar Numpy en esta pregunta.

In [65]:
for index, value in np.ndenumerate(d):
    if d_min < value < d_media:
        f[index] = 25
    elif d_media < value < d_max:
        f[index] = 75
    elif value == d_media:
        f[index] = 50
    elif value == d_min:
        f[index] = 0
    elif value == d_max:
        f[index] = 100

17. Imprime d y f. ¿Tienes tu f esperada?

In [66]:
print(d)

print(f)

[[[1.00550821 1.07417117 1.83432173 1.34577146 1.05123209]
  [1.5039223  1.99534268 1.1603097  1.09384193 1.44810038]]

 [[1.62141364 1.20106772 1.68329497 1.96875763 1.56051962]
  [1.02776128 1.35013522 1.57976256 1.2164994  1.56371725]]

 [[1.57863805 1.25849108 1.7694041  1.88466783 1.74222569]
  [1.09044981 1.60514093 1.81166067 1.15924428 1.69933908]]]
[[[  0.  25.  75.  25.  25.]
  [ 75. 100.  25.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  75.  25.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  75.  25.  75.]]]


18. Pregunta extra: en lugar de utilizar números (p. ej. 0, 25, 50, 75 y 100), ¿cómo utilizar valores de cadena 
("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas que el resultado sea
array([[ 'D', 'D', 'D', 'B', 'D'],
        [ 'D', 'D', 'B', 'B', 'B'],
        [ 'D', 'B', 'D', 'D', 'D'],

       [[ 'B', 'B', 'B', 'B', 'E'],
        [[ 'D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'A', 'D', 'D']])
De nuevo, no necesitas Numpy en esta pregunta.

In [68]:
g = np.empty_like(d, dtype=str)

for index, value in np.ndenumerate(d):
    if d_min < value < d_media:
        g[index] = 'B'
    elif d_media < value < d_max:
        g[index] = 'D'
    elif value == d_media:
        g[index] = 'C'
    elif value == d_min:
        g[index] = 'A'
    elif value == d_max:
        g[index] = 'E'
        
print(g)

[[['A' 'B' 'D' 'B' 'B']
  ['D' 'E' 'B' 'B' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'D' 'B' 'D']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'B' 'D']]]
