In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [4]:
#2. Print the NUMPY version and the configuration.

print('Numpy version', np.__version__)

print('Numpy configuration:')

print(np.show_config())

Numpy version 1.23.5
Numpy configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/veronicamoncada/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/veronicamoncada/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/veronicamoncada/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/veronicamoncada/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    foun

In [7]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.rand(2, 3, 5)

print (a)

[[[0.45903858 0.89148101 0.50294407 0.23100222 0.43033105]
  [0.14605464 0.65527292 0.80271409 0.41201287 0.01956378]
  [0.17405893 0.99604293 0.8578964  0.47486763 0.03349679]]

 [[0.97478823 0.14662356 0.00803548 0.58842188 0.71800807]
  [0.13022726 0.81008668 0.14865979 0.17513357 0.10110561]
  [0.36388669 0.73272404 0.1062318  0.76064662 0.60160712]]]


In [8]:
a = np.random.randn(2, 3, 5)

print (a)

[[[ 0.41880656 -0.48459219  0.41230678 -1.1424129  -0.27512112]
  [ 0.05755879 -0.85683102  0.47753933 -0.99844484 -0.86192886]
  [ 0.55525789 -1.32735031  0.82161229  0.9475071   0.53461324]]

 [[-0.54943021  0.55766461  1.25999663 -0.02428416 -0.27858845]
  [ 0.63447391 -0.95375749 -1.80899485 -0.38843784  1.01486476]
  [-0.68888694  0.56926575 -0.96781266  0.84097979 -0.18777473]]]


In [9]:
a = np.random.random_sample((2, 3, 5))

print(a)

[[[0.17515332 0.24326526 0.15694728 0.3094235  0.95641533]
  [0.457233   0.57004941 0.98974303 0.6911829  0.64650684]
  [0.38115842 0.34905633 0.99029817 0.48356186 0.59500361]]

 [[0.54069972 0.31951174 0.95932312 0.68955641 0.84479876]
  [0.31040161 0.30711163 0.68444956 0.00264807 0.36076726]
  [0.65050466 0.50631076 0.31134523 0.504406   0.34159404]]]


In [11]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))

#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
#7.Do a and b have the same size? How do you prove that in Python code?

if a.size == b.size:
    print('a and b have the same size')

a and b have the same size


In [15]:
#8. Are you able to add a and b? Why or why not?

if a.shape == b.shape:
    print('you are able to add a and b')
    
else:
    print('you are not able to add a and b')


you are not able to add a and b


In [33]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
# Assign the transposed array to varialbe "c".


c = b.reshape(2, 3, 5)

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [21]:
print(a.shape)

(2, 3, 5)


In [25]:
print(b.shape)

(5, 2, 3)


In [22]:
print(c.shape)

(3, 2, 5)


In [24]:
print(b.T.shape)

(3, 2, 5)


In [36]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c

print(d)

[[[1.17515332 1.24326526 1.15694728 1.3094235  1.95641533]
  [1.457233   1.57004941 1.98974303 1.6911829  1.64650684]
  [1.38115842 1.34905633 1.99029817 1.48356186 1.59500361]]

 [[1.54069972 1.31951174 1.95932312 1.68955641 1.84479876]
  [1.31040161 1.30711163 1.68444956 1.00264807 1.36076726]
  [1.65050466 1.50631076 1.31134523 1.504406   1.34159404]]]


In [37]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)

[[[0.17515332 0.24326526 0.15694728 0.3094235  0.95641533]
  [0.457233   0.57004941 0.98974303 0.6911829  0.64650684]
  [0.38115842 0.34905633 0.99029817 0.48356186 0.59500361]]

 [[0.54069972 0.31951174 0.95932312 0.68955641 0.84479876]
  [0.31040161 0.30711163 0.68444956 0.00264807 0.36076726]
  [0.65050466 0.50631076 0.31134523 0.504406   0.34159404]]]


In [38]:
print(d)

[[[1.17515332 1.24326526 1.15694728 1.3094235  1.95641533]
  [1.457233   1.57004941 1.98974303 1.6911829  1.64650684]
  [1.38115842 1.34905633 1.99029817 1.48356186 1.59500361]]

 [[1.54069972 1.31951174 1.95932312 1.68955641 1.84479876]
  [1.31040161 1.30711163 1.68444956 1.00264807 1.36076726]
  [1.65050466 1.50631076 1.31134523 1.504406   1.34159404]]]


In [ ]:
# a = np.random.random_sample((2, 3, 5))
# b = b = np.ones((5, 2, 3))

In [40]:
#12. Multiply a and c. Assign the result to e.

e = a * c

print(e)

[[[0.17515332 0.24326526 0.15694728 0.3094235  0.95641533]
  [0.457233   0.57004941 0.98974303 0.6911829  0.64650684]
  [0.38115842 0.34905633 0.99029817 0.48356186 0.59500361]]

 [[0.54069972 0.31951174 0.95932312 0.68955641 0.84479876]
  [0.31040161 0.30711163 0.68444956 0.00264807 0.36076726]
  [0.65050466 0.50631076 0.31134523 0.504406   0.34159404]]]


In [41]:
#13. Does e equal to a? Why or why not?

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [46]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = d.max()

d_min = d.min()

d_mean = d.mean()



In [48]:
print(d_max)

print(d_min)

print(d_mean)

1.9902981682981205
1.0026480736878056
1.510947561904306


In [ ]:
#15. Now we want to label the values in d. 
# First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [55]:
f = np.empty((2, 3, 5))

print(f)

[[[0.17515332 0.24326526 0.15694728 0.3094235  0.95641533]
  [0.457233   0.57004941 0.98974303 0.6911829  0.64650684]
  [0.38115842 0.34905633 0.99029817 0.48356186 0.59500361]]

 [[0.54069972 0.31951174 0.95932312 0.68955641 0.84479876]
  [0.31040161 0.30711163 0.68444956 0.00264807 0.36076726]
  [0.65050466 0.50631076 0.31134523 0.504406   0.34159404]]]


In [53]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

f = np.empty(c.shape)

d_min = np.min(c)
d_max = np.max(c)
d_mean = np.mean(c)

for v in range(c.shape[0]):
    for e in range(c.shape[1]):
        for r in range(c.shape[2]):
            if 
    





SyntaxError: invalid syntax (1381370722.py, line 11)